version: "3"
services:
  lma-postgres:
    image: "postgres:14"
    container_name: lma-postgres
    volumes:
      - lma-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgresdb
    networks:
    - strapi

  lma-backend:
    build: ./LMA-BACKEND
    container_name: lma-backend
    environment:
      - DB_SERVER=lma-postgres
    ports:
      - 1338:1338
    volumes:
      - ./LMA-BACKEND/config:/opt/app/config
      - ./LMA-BACKEND/src:/opt/app/src
      - ./LMA-BACKEND/package.json:/opt/package.json
      - ./LMA-BACKEND/yarn.lock:/opt/yarn.lock
      - ./LMA-BACKEND/.env:/opt/app/.env
      - ./LMA-BACKEND/public/uploads:/opt/app/public/uploads
    links:
      - lma-postgres
    networks:
      - strapi
    depends_on:
      - lma-postgres

  lma-frontend:
    build: ./LMA-FRONTEND
    container_name: lma-frontend
    volumes:
      - ./LMA-FRONTEND/src:/LMA-FRONTEND/src
      - ./LMA-FRONTEND/.env:/LMA-FRONTEND/.env
    environment:
      CHOKIDAR_USEPOLLING: true

    ports:
      - 3000:3000
    links:
      - lma-backend
networks:
  strapi:
    name: Strapi
    driver: bridge
    external: true
volumes:
  lma-data:
